language: elixir
elixir: '1.8'
install:
  - mix local.rebar --force
  - mix local.hex --force
  - mix deps.get
  - mix ecto.setup
  - cd assets && npm install; cd ..
script:
  - phantomjs --wd &
  - mix test